version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - set -euo pipefail
      - echo "Vendoring SonarLess CLI script..." 
      - mkdir -p "$PWD/.tools"
      - curl -fsSL https://raw.githubusercontent.com/gitricko/sonarless/main/makefile.sh -o "$PWD/.tools/sonarless"
      - chmod +x "$PWD/.tools/sonarless"
      - export PATH="$PWD/.tools:$PATH"
      - echo "Verifying SonarLess availability..."
      - sonarless --help || sonarless -h || { echo "SonarLess not available on PATH"; ls -la "$PWD/.tools"; echo "PATH: $PATH"; exit 1; }

  pre_build:
    commands:
      - echo "Preparing for SonarLess scan..."

  build:
    commands:
      - echo "Running SonarLess scan (gate)..."
      - sonarless scan

  post_build:
    commands:
      - echo "Post-build steps..."

artifacts:
  files:
    - '**/*'
