version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - 'set -euo pipefail'
      - 'echo Installing dependencies...'
      - 'npm ci --verbose || npm install --legacy-peer-deps --verbose'
      - 'echo Installing SonarLess...'
      - 'mkdir -p .tools'
      - 'curl -fsSL https://raw.githubusercontent.com/gitricko/sonarless/main/makefile.sh -o ./.tools/sonarless'
      - 'chmod +x ./.tools/sonarless'
      - 'echo Verifying SonarLess availability...'
      - './.tools/sonarless --help || ./.tools/sonarless -h'
  pre_build:
    commands:
      - 'echo Pre-build phase...'
  build:
    commands:
      - 'echo Building React app...'
      - 'npm run build'
      - 'echo Running SonarLess scan (gate)...'
      - './.tools/sonarless scan'
  post_build:
    commands:
      - 'echo Build completed at `date`'

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: yes
