version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing Sonarless CLI..."
      - curl -sSfL https://raw.githubusercontent.com/gitricko/sonarless/main/install.sh | bash
      # Ensure sonarless is in PATH
      - export PATH=$PATH:$HOME/.local/bin
      - sonarless --version
 
  pre_build:
    commands:
      - echo "Preparing for Sonarless scan..."
 
  build:
    commands:
      - echo "Running Sonarless scan..."
      - sonarless scan
      - echo "Sonarless scan completed successfully."
 
  post_build:
    commands:
      - echo "Post-build steps (if any)..."
 
artifacts:
  files:
    - '**/*'
