version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - set -euo pipefail
      - echo "Installing SonarLess..."
      - curl -fsSL https://raw.githubusercontent.com/gitricko/sonarless/main/install.sh -o /tmp/sonarless-install.sh
      - bash /tmp/sonarless-install.sh

      # Make the installed script executable and expose it on PATH
      - echo "Linking SonarLess to a real binary path..."
      - |
        if [ -f "$HOME/.sonarless/makefile.sh" ]; then
          chmod +x "$HOME/.sonarless/makefile.sh"
          ln -sf "$HOME/.sonarless/makefile.sh" /usr/local/bin/sonarless || true
          ln -sf "$HOME/.sonarless/makefile.sh" "$HOME/.local/bin/sonarless" || true
          export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"
        fi
        if ! command -v sonarless >/dev/null 2>&1; then
          echo "ERROR: sonarless binary not found after install; printing directories..."
          echo "PATH: $PATH"
          ls -la "$HOME/.sonarless" || true
          ls -la "$HOME/.local/bin" || true
          ls -la /usr/local/bin || true
          exit 1
        fi
      - echo "Checking SonarLess version..."
      - sonarless --version

  pre_build:
    commands:
      - echo "Preparing for SonarLess scan..."

  build:
    commands:
      - echo "Running SonarLess scan (gate)..."
      - sonarless scan

  post_build:
    commands:
      - echo "Post-build steps..."
artifacts:
  files:
    - '**/*'
