version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing NPM dependencies..."
      - npm cache clean --force
      - npm install --verbose
      - echo "Installing SonarLess..."
      - curl -fsSL https://raw.githubusercontent.com/gitricko/sonarless/main/install.sh | bash

  pre_build:
    commands:
      - echo "Pre-build phase..."

  build:
    commands:
      - echo "Verifying SonarLess installation..."
      - sonarless --version || sonarless --help || { echo "SonarLess not installed"; exit 1; }
      - echo "Running SonarLess scan..."
      - sonarless scan
      - echo "Building React app..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed at `date`"

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
