version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Cleaning npm cache...
      - npm cache clean --force
      - echo Installing NPM dependencies...
      - npm install --verbose
  pre_build:
    commands:
      - echo Pre-build checks...
  build:
    commands:
      - echo Building React app...
      - npm run build
      - echo Installing SonarLess...
      - curl -fsSL https://raw.githubusercontent.com/gitricko/sonarless/main/install.sh | bash
      - echo Checking SonarLess installation...
      - sonarless --version || sonarless --help || { echo "SonarLess not installed"; exit 1; }
      - echo Running SonarLess scan...
      - sonarless scan
  post_build:
    commands:
      - echo Build completed at `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: yes
cache:
  paths:
    - 'node_modules/**/*'
